services:
  - type: web
    name: online-shopping
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn OnlineShopping.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10
